---
title: "Introduction to R"
author: "Adam M. Wilson"
date: "February 11, 2015"
output: 
  md_document:
    variant: markdown_github
---

```{r, echo=FALSE, message=FALSE, results='hide', purl=FALSE}
## This chunk automatically generates a text .R version of this script when running within knitr.  You do not need to run this...
input  = knitr::current_input()  # filename of input document
output = paste(tools::file_path_sans_ext(input), 'R', sep = '.')
knitr::purl(input,output,documentation=2,quiet=T)
repo="http://github.com/adammwilson/SpatialAnalysisTutorials/blob/master/R_Introduction"
```


#  Introduction
This script is available:

  * [SpatialAnalysisTutorials repository](`r repo`)
  * Plain text (.R) with commented text [here](`r paste0(repo,"/",output)`)
 
```{r message=F,warning=FALSE}
library(knitr)
library(ggplot2)

presentation_theme <- theme_grey()+
  theme(text = element_text(size = 25, colour = "black"))

```


If you don't have the packages above, install them in the package manager or by running `install.packages("ggplot2")`. 

## Vectors

```{r echo=FALSE}
1:10
````


## Matrices


## Working with Raster Data
```{r}
library(raster)
```



# Coda



```{r, echo=FALSE, message=FALSE, results='hide', purl=FALSE}
input=tools::file_path_sans_ext(input)
file.rename(paste(input, 'md', sep = '.'),"README.md")
```



